### ISSUE TITLE
Error in "curried" section?

### ISSUE THREAD

**Issue by jonathanGB** [go-functional/core#9]
Hey,

I was wondering if there was an error in the last snippet of the "curried" section; it looks to me like like the inner function should be returned to satisfy the outer signature.

Current:
<img width="414" alt="image" src="https://user-images.githubusercontent.com/8869660/28558759-25cb015a-70c8-11e7-8a5e-b6f070266be9.png">

Proposal:
```go
func getHandler(cl *sql.DB) http.HandlerFunc {
  return func(w http.ResponseWriter, r *http.Request) {
    ...
  }
}
```

**Comment by arschles** [comment]
@jonathanGB yes, it looks like you're right. I don't think I wrote tests for that section, so that explains how it got into master while it didn't compile. Would you care to submit a PR with the fix?
